# Generated by Django 5.1.7 on 2025-03-07 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='combine_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default='null', max_length=5)),
                ('weight', models.IntegerField(default='null')),
                ('fourty_time', models.FloatField(default='null', max_length=5)),
                ('bench_press', models.IntegerField(default='null')),
                ('cone_3', models.FloatField(default='null', max_length=4)),
                ('broad_jump', models.FloatField(default='null', max_length=6)),
                ('vertical_jump', models.FloatField(default='null', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_address', models.EmailField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='null', max_length=20)),
                ('last_name', models.CharField(default='null', max_length=30)),
                ('ranking', models.IntegerField(default=2)),
                ('position', models.CharField(default='null', max_length=4)),
                ('age', models.IntegerField(default=20)),
                ('college', models.CharField(default='null', max_length=30)),
                ('combine_stats', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='core.combine_stats')),
            ],
        ),
    ]
