# Generated by Django 5.1.7 on 2025-03-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_combinestats_remove_player_ranking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='mode',
            field=models.CharField(choices=[('full', 'Full Draft'), ('quick', 'Quick Draft'), ('custom', 'Custom Draft')], default='quick', max_length=10),
        ),
    ]
