# Generated by Django 5.1.7 on 2025-04-01 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_draft_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='mode',
        ),
    ]
