# Generated by Django 5.1.7 on 2025-04-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_draft_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
