# Generated by Django 5.1.7 on 2025-04-05 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_draft_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='college_touchdowns',
        ),
        migrations.RemoveField(
            model_name='player',
            name='college_yards',
        ),
        migrations.RemoveField(
            model_name='player',
            name='combine_stats',
        ),
        migrations.RemoveField(
            model_name='player',
            name='projected_round',
        ),
    ]
