# Generated by Django 5.1.7 on 2025-04-07 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_player_college_touchdowns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='selected_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_in_draft', to='core.draftpick'),
        ),
        migrations.AlterField(
            model_name='draftpick',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='core.draft'),
        ),
    ]
