# Generated by Django 5.1.7 on 2025-04-09 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_draft_selected_player_alter_draftpick_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='player_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_in_draft', to='core.player'),
        ),
    ]
