# Generated by Django 5.1.7 on 2025-04-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_draft_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='name',
            field=models.CharField(default='Untitled Draft', max_length=100),
        ),
    ]
